name = "myavka-chat-do"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[durable_objects]
bindings = [{ name = "CHAT_DO", class_name = "ChatRoom" }]
